// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC4rVrjTfbidDGmVyTdp_hgvCF3RPo5HT0',
    appId: '1:953453969755:web:f79503185d672ae8ecda7e',
    messagingSenderId: '953453969755',
    projectId: 'bibigoairplane',
    authDomain: 'bibigoairplane.firebaseapp.com',
    storageBucket: 'bibigoairplane.firebasestorage.app',
    measurementId: 'G-M3T82R62W0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCZGvG95c3YdEOtH2tPbttwqb_4cqrUao4',
    appId: '1:953453969755:android:fa5c53a4318f1a6cecda7e',
    messagingSenderId: '953453969755',
    projectId: 'bibigoairplane',
    storageBucket: 'bibigoairplane.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyANVPfH_i_1spK_4gkNUWndFgaSFKD7gvc',
    appId: '1:953453969755:ios:9d1aab8dab69b839ecda7e',
    messagingSenderId: '953453969755',
    projectId: 'bibigoairplane',
    storageBucket: 'bibigoairplane.firebasestorage.app',
    iosBundleId: 'com.example.appbibigoairplane',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyANVPfH_i_1spK_4gkNUWndFgaSFKD7gvc',
    appId: '1:953453969755:ios:9d1aab8dab69b839ecda7e',
    messagingSenderId: '953453969755',
    projectId: 'bibigoairplane',
    storageBucket: 'bibigoairplane.firebasestorage.app',
    iosBundleId: 'com.example.appbibigoairplane',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC4rVrjTfbidDGmVyTdp_hgvCF3RPo5HT0',
    appId: '1:953453969755:web:3bdd0522f38d0b71ecda7e',
    messagingSenderId: '953453969755',
    projectId: 'bibigoairplane',
    authDomain: 'bibigoairplane.firebaseapp.com',
    storageBucket: 'bibigoairplane.firebasestorage.app',
    measurementId: 'G-Q1HXZSPT75',
  );
}
