final Map<String, String> cidadeParaIATACode = {
  'sao paulo': 'SAO',
  'rio de janeiro': 'RIO',
  'brasilia': 'BSB',
  'teresina': 'THE',
  'campinas': 'VCP',
  'recife': 'REC',
  'fortaleza': 'FOR',
  'salvador': 'SSA',
  'porto alegre': 'POA',
  'curitiba': 'CWB',
  'manaus': 'MAO',
  'goiania': 'GYN',
  'belo horizonte': 'CNF',
  'natal': 'NAT',
  'joao pessoa': 'JPA',
  'maceio': 'MCZ',
  'aracaju': 'AJU',
  'belem': 'BEL',
  'palmas': 'PMW',
  'cuiaba': 'CGB',
  'campo grande': 'CGR',
  'florianopolis': 'FLN',
  'vitoria': 'VIX',
  'macapa': 'MCP',
  'porto velho': 'PVH',
  'rio branco': 'RBR',
  'boa vista': 'BVB',
  'santarem': 'STM'
};
  